### ISSUE TITLE
Crank up the hunger?

### ISSUE THREAD

**Issue by djdefi** [es-na-battlesnake/snakes#129]
Looking at a couple recent losses games, I think if we gained length faster we may have had the upper hand. We remain pretty short while other snakes are getting pretty big such as https://play.battlesnake.com/g/1971de33-9528-43eb-bfcc-e3d86854ac49/

If we are longer we have better board control earlier on I believe. 

Would this just be an adjustment here?  https://github.com/es-na-battlesnake/snakes/blob/36b684bcb793b3df108b5ef2c7b65e268f6e3ef4/snakes/go/spring-league-2022/logic.go#L452

cc: @bevns

**Comment by bevns** [comment]
We really should change the name of that other snake now that we have Pathy. Pathy is the one behind `gobeans`. 

Health adjustment should actually happen here: https://github.com/es-na-battlesnake/snakes/blob/main/snakes/go/pathy-snake/pathing.go#L214
