### ISSUE TITLE
Implement branch deploys and a staging environment

### ISSUE THREAD

**Issue by djdefi** [es-na-battlesnake/snakes#252]
Using https://github.com/github/branch-deploy

**Comment by bevns** [comment]
Production Branch deploys are now live!!! 🚀 

Outstanding task is to implement Staging environment and setup proper deploy commands for it.

**Comment by GrantBirki** [comment]
Woohoo! Branch deployments for sneks! :snake:

**Comment by bevns** [comment]
@djdefi I am gonna close this out since branch deploys are working. 

We didn't do anything with a staging env but if we need that we can open a separate issue?
