### ISSUE TITLE
Restructure and rename repo to allow running more than ruby

### ISSUE THREAD

**Issue by djdefi** [es-na-battlesnake/snakes#80]
We want to write snakes in other languages like Go, Python, or Rockstar. We don't want to spin up multiple container instances (more $$ and management).

We can cram the other services into our Docker image, and run them the same way on different ports 🎉 .

**Comment by bevns** [comment]
we still got some work to do on this yo. re-opening

**Comment by djdefi** [comment]
I think we can call this done for now.
